-- @db file
-- The engine re-parses every CREATE statement stored in sqlite_schema.
-- SQLite stores the text as written (after "CREATE TABLE"), so the schema
-- contains quoted identifiers of all three kinds, keywords used as names,
-- comments and newlines inside the definition, multi-word and
-- parameterized type names, named constraints, REFERENCES/FOREIGN KEY
-- clauses, CHECK, DEFAULT forms, COLLATE and conflict clauses. A table
-- made by CREATE TABLE ... AS SELECT has schema text generated by SQLite.
-- @phase sqlite
CREATE TABLE orders(id INTEGER PRIMARY KEY, placed TEXT NOT NULL);
create   table IF NOT EXISTS "Order Items" (
  "item id" INTEGER PRIMARY KEY ON CONFLICT REPLACE, -- the key
  [unit price] DECIMAL(10, 2) NOT NULL DEFAULT 0,
  `qty` int CONSTRAINT qty_ok CHECK (qty >= 0) DEFAULT 1,
  /* free text */ note VARCHAR(20) COLLATE NOCASE DEFAULT 'none',
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT uq_note UNIQUE (order_id, note) ON CONFLICT IGNORE,
  FOREIGN KEY (order_id) REFERENCES orders (id),
  CHECK ([unit price] >= 0)
);
CREATE TABLE "select"("from" TEXT, "where" INTEGER, "group" REAL);
CREATE TABLE odd_types(a UNSIGNED BIG INT, b DOUBLE PRECISION, c CHARACTER VARYING(255), d NATIVE CHARACTER(70), e, f BOOLEAN, g DATETIME);
CREATE TABLE defaults(
  id INTEGER PRIMARY KEY, a DEFAULT -1, b DEFAULT +2.5, c DEFAULT (1 + 2), d DEFAULT 'it''s',
  e DEFAULT NULL, f DEFAULT TRUE, g DEFAULT x'ABCD', h TEXT DEFAULT (upper('abc')), i DEFAULT 0x10
);
INSERT INTO orders VALUES (1, '2024-01-02'), (2, '2024-03-04');
INSERT INTO "Order Items"("item id", [unit price], qty, note, order_id) VALUES (1, '9.99', 2, 'First', 1), (2, 5, '3', 'Second', 1), (3, 0.5, 10, NULL, 2);
INSERT INTO "Order Items"(order_id) VALUES (2);
INSERT INTO "select" VALUES ('x', '42', '1.5'), ('y', 'abc', 7);
INSERT INTO odd_types VALUES ('12', '3', 4, 5, '6', 1, '2024-05-06');
INSERT INTO defaults(id) VALUES (1);
INSERT INTO defaults(id, a, h) VALUES (2, 'set', 'set');
CREATE TABLE ctas AS SELECT "item id" AS item, qty * [unit price] AS total, note FROM "Order Items";
-- @phase engine
SELECT "item id", [unit price], typeof([unit price]), `qty`, note, order_id FROM "Order Items" ORDER BY 1;
SELECT o.placed, sum(i.qty * i."unit price") FROM orders o JOIN "Order Items" i ON i.order_id = o.id GROUP BY o.id ORDER BY o.id;
SELECT "item id" FROM "Order Items" WHERE note = 'FIRST';
SELECT "from", "where", typeof("where"), "group", typeof("group") FROM "select" ORDER BY "from";
SELECT a, typeof(a), b, typeof(b), c, typeof(c), d, typeof(d), e, typeof(e), f, g FROM odd_types;
SELECT * FROM defaults ORDER BY id;
SELECT typeof(c), typeof(f), hex(g) FROM defaults WHERE id = 1;
SELECT item, total, note FROM ctas ORDER BY item;
SELECT typeof(item), typeof(total) FROM ctas WHERE item = 1;
SELECT count(*) FROM sqlite_schema WHERE tbl_name = 'Order Items';
-- Affinity from the parsed types drives comparisons.
SELECT count(*) FROM odd_types WHERE a = '12' AND c = 4;
SELECT "from" FROM "select" WHERE "where" = '42';
