-- CAST(x AS NUMERIC): text becomes INTEGER or REAL (whichever fits the
-- longest numeric prefix); INTEGER and REAL values are left unchanged.

SELECT CAST('42' AS NUMERIC), CAST('3.5' AS NUMERIC), CAST('3.0' AS NUMERIC), CAST('1e2' AS NUMERIC);
SELECT typeof(CAST('42' AS NUMERIC)), typeof(CAST('3.5' AS NUMERIC)), typeof(CAST('3.0' AS NUMERIC)), typeof(CAST('1e2' AS NUMERIC));
-- A REAL stays REAL even when it has no fractional part.
SELECT CAST(3.0 AS NUMERIC), typeof(CAST(3.0 AS NUMERIC)), CAST(5 AS NUMERIC), typeof(CAST(5 AS NUMERIC));
-- Prefixes and junk.
SELECT CAST('12abc' AS NUMERIC), CAST('1.5abc' AS NUMERIC), CAST('abc' AS NUMERIC), CAST('' AS NUMERIC);
SELECT CAST('  7  ' AS NUMERIC), CAST('-0' AS NUMERIC), CAST('0x10' AS NUMERIC);
-- Too big for INTEGER: REAL.
SELECT CAST('9223372036854775807' AS NUMERIC), CAST('9223372036854775808' AS NUMERIC);
SELECT typeof(CAST('9223372036854775808' AS NUMERIC));
-- Blobs are read as text.
SELECT CAST(x'3132' AS NUMERIC), CAST(x'332E35' AS NUMERIC);
SELECT CAST(NULL AS NUMERIC);
-- DECIMAL, BOOLEAN, DATE and unrecognized type names mean NUMERIC.
SELECT CAST('4.0' AS DECIMAL(10, 2)), CAST('1' AS BOOLEAN), CAST('2.50' AS NUMBER), CAST('8.0' AS WHATEVER);
SELECT typeof(CAST('4.0' AS DECIMAL(10, 2))), typeof(CAST('8.0' AS WHATEVER));
-- Casting table data.
CREATE TABLE t(id INTEGER, v TEXT);
INSERT INTO t VALUES (1, '10'), (2, '2.5'), (3, '1e1'), (4, 'ten'), (5, '7.0'), (6, NULL);
SELECT id, CAST(v AS NUMERIC), typeof(CAST(v AS NUMERIC)) FROM t ORDER BY id;
SELECT id FROM t WHERE CAST(v AS NUMERIC) = 10 ORDER BY id;
SELECT id FROM t ORDER BY CAST(v AS NUMERIC), id;
