-- IS DISTINCT FROM and IS NOT DISTINCT FROM are synonyms for IS NOT and IS.

SELECT 1 IS DISTINCT FROM 1, 1 IS DISTINCT FROM 2, 1 IS NOT DISTINCT FROM 1, 1 IS NOT DISTINCT FROM 2;
SELECT NULL IS DISTINCT FROM NULL, NULL IS NOT DISTINCT FROM NULL;
SELECT NULL IS DISTINCT FROM 1, 1 IS DISTINCT FROM NULL, NULL IS NOT DISTINCT FROM 0;
SELECT typeof(NULL IS DISTINCT FROM 1);
SELECT 1 IS NOT DISTINCT FROM 1.0, 'a' IS DISTINCT FROM 'A', '1' IS DISTINCT FROM 1;
-- Keywords are case-insensitive.
SELECT 1 is distinct from 2, 1 Is Not Distinct From 1;
-- Rows with NULLs.
CREATE TABLE t(id INTEGER, a TEXT, b TEXT);
INSERT INTO t VALUES (1, 'x', 'x'), (2, 'x', 'y'), (3, NULL, 'y'), (4, 'x', NULL), (5, NULL, NULL);
SELECT id, a IS DISTINCT FROM b, a IS NOT DISTINCT FROM b, a <> b FROM t ORDER BY id;
SELECT id FROM t WHERE a IS DISTINCT FROM b ORDER BY id;
SELECT id FROM t WHERE a IS NOT DISTINCT FROM b ORDER BY id;
SELECT id FROM t WHERE a IS NOT DISTINCT FROM 'x' ORDER BY id;
-- Equivalent to IS / IS NOT on every row.
SELECT id FROM t WHERE (a IS DISTINCT FROM b) <> (a IS NOT b) ORDER BY id;
-- Precedence: binds like '=' so arithmetic happens first.
SELECT 1 + 1 IS DISTINCT FROM 2, 2 * 2 IS NOT DISTINCT FROM 4;
-- Affinity applies as with '='.
CREATE TABLE u(i INTEGER);
INSERT INTO u VALUES (7);
SELECT i IS NOT DISTINCT FROM '7', i IS DISTINCT FROM '7.0', i IS DISTINCT FROM 'seven' FROM u;
-- Syntax error: DISTINCT without FROM.
SELECT 1 IS DISTINCT 2;
