-- IS NULL, IS NOT NULL, and the postfix forms ISNULL, NOTNULL, NOT NULL.

SELECT NULL IS NULL, 1 IS NULL, '' IS NULL, 0 IS NULL, x'' IS NULL;
SELECT NULL IS NOT NULL, 1 IS NOT NULL, '' IS NOT NULL;
SELECT NULL ISNULL, 1 ISNULL, NULL NOTNULL, 1 NOTNULL;
SELECT NULL NOT NULL, 1 NOT NULL, 'x' NOT NULL;
SELECT typeof(NULL IS NULL), typeof(1 NOTNULL);
-- Expressions that evaluate to NULL.
SELECT 1 + NULL IS NULL, 1 / 0 IS NULL, NULL || 'a' IS NULL, (NULL = NULL) IS NULL;
-- IS NULL results are never NULL themselves.
SELECT (NULL IS NULL) IS NULL, (NULL NOTNULL) IS NULL;
-- Combined with logic.
SELECT NULL IS NULL AND 1 IS NOT NULL, NOT NULL IS NULL, NOT 1 ISNULL;
-- In WHERE.
CREATE TABLE t(id INTEGER, a TEXT, b INTEGER);
INSERT INTO t VALUES (1, 'x', 10), (2, NULL, 20), (3, 'z', NULL), (4, NULL, NULL), (5, '', 0);
SELECT id FROM t WHERE a IS NULL ORDER BY id;
SELECT id FROM t WHERE a IS NOT NULL ORDER BY id;
SELECT id FROM t WHERE a ISNULL ORDER BY id;
SELECT id FROM t WHERE b NOTNULL ORDER BY id;
SELECT id FROM t WHERE b NOT NULL ORDER BY id;
SELECT id FROM t WHERE a IS NULL AND b IS NULL ORDER BY id;
SELECT id FROM t WHERE a IS NULL OR b IS NULL ORDER BY id;
SELECT id FROM t WHERE a || b IS NOT NULL ORDER BY id;
SELECT id, a IS NULL, b NOTNULL, a NOT NULL FROM t ORDER BY id;
