-- EXCLUDE GROUP removes the current row and all its peers from the frame;
-- EXCLUDE TIES removes the peers but keeps the current row. Peers are rows
-- with equal ORDER BY values. The frames here are chosen so that frame
-- membership does not depend on the order of peers.
CREATE TABLE e(id INTEGER PRIMARY KEY, k INTEGER, v INTEGER);
INSERT INTO e VALUES (1, 1, 1), (2, 1, 2), (3, 2, 4), (4, 3, 8), (5, 3, 16), (6, 3, 32), (7, 4, 64);

-- Whole-partition ROWS frame.
SELECT id, k, sum(v) OVER (ORDER BY k ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE GROUP),
  sum(v) OVER (ORDER BY k ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE TIES) FROM e ORDER BY id;

-- RANGE frames.
SELECT id, k, sum(v) OVER (ORDER BY k RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE GROUP),
  sum(v) OVER (ORDER BY k RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE TIES) FROM e ORDER BY id;
SELECT id, k, sum(v) OVER (ORDER BY k RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE GROUP),
  sum(v) OVER (ORDER BY k RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE TIES) FROM e ORDER BY id;

-- GROUPS frames.
SELECT id, k, sum(v) OVER (ORDER BY k GROUPS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE GROUP),
  sum(v) OVER (ORDER BY k GROUPS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE TIES) FROM e ORDER BY id;

-- The peer group is the only content of the frame: EXCLUDE GROUP leaves it empty.
SELECT id, count(*) OVER w, sum(v) OVER w FROM e WINDOW w AS (ORDER BY k RANGE CURRENT ROW EXCLUDE GROUP) ORDER BY id;
SELECT id, count(*) OVER w, sum(v) OVER w FROM e WINDOW w AS (ORDER BY k GROUPS CURRENT ROW EXCLUDE TIES) ORDER BY id;

-- Compare all four EXCLUDE options side by side.
SELECT id, k,
  sum(v) OVER (ORDER BY k GROUPS BETWEEN CURRENT ROW AND 1 FOLLOWING EXCLUDE NO OTHERS),
  sum(v) OVER (ORDER BY k GROUPS BETWEEN CURRENT ROW AND 1 FOLLOWING EXCLUDE CURRENT ROW),
  sum(v) OVER (ORDER BY k GROUPS BETWEEN CURRENT ROW AND 1 FOLLOWING EXCLUDE GROUP),
  sum(v) OVER (ORDER BY k GROUPS BETWEEN CURRENT ROW AND 1 FOLLOWING EXCLUDE TIES)
FROM e ORDER BY id;

-- With unique ORDER BY keys, EXCLUDE GROUP = EXCLUDE CURRENT ROW and
-- EXCLUDE TIES = EXCLUDE NO OTHERS.
SELECT id, sum(v) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE GROUP),
  sum(v) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE TIES) FROM e ORDER BY id;

-- Without ORDER BY, all rows are peers: EXCLUDE GROUP empties the frame and
-- EXCLUDE TIES keeps only the current row.
SELECT id, sum(v) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE GROUP),
  sum(v) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE TIES) FROM e ORDER BY id;

-- count and max with EXCLUDE TIES / GROUP.
SELECT id, count(*) OVER w1, max(v) OVER w1, count(*) OVER w2, max(v) OVER w2 FROM e
WINDOW w1 AS (ORDER BY k RANGE BETWEEN 2 PRECEDING AND CURRENT ROW EXCLUDE GROUP),
       w2 AS (ORDER BY k RANGE BETWEEN 2 PRECEDING AND CURRENT ROW EXCLUDE TIES) ORDER BY id;

-- Per partition (k > 2 vs k <= 2).
SELECT id, sum(v) OVER (PARTITION BY k > 2 ORDER BY k RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE GROUP) FROM e ORDER BY id;

-- Error: EXCLUDE without a frame specification.
SELECT sum(v) OVER (ORDER BY k EXCLUDE TIES) FROM e;
