-- Chains of compound operators are evaluated left to right with equal
-- precedence: "A UNION B EXCEPT C" is "(A UNION B) EXCEPT C".
CREATE TABLE a(v INTEGER);
CREATE TABLE b(v INTEGER);
CREATE TABLE c(v INTEGER);
INSERT INTO a VALUES (1), (2), (3);
INSERT INTO b VALUES (3), (4);
INSERT INTO c VALUES (1), (4), (5);

SELECT v FROM a UNION SELECT v FROM b EXCEPT SELECT v FROM c ORDER BY v;
SELECT v FROM a EXCEPT SELECT v FROM c UNION SELECT v FROM b ORDER BY v;
SELECT v FROM a UNION SELECT v FROM b INTERSECT SELECT v FROM c ORDER BY v;
SELECT v FROM a INTERSECT SELECT v FROM c UNION SELECT v FROM b ORDER BY v;
SELECT v FROM a UNION SELECT v FROM c INTERSECT SELECT v FROM b ORDER BY v;
-- UNION ALL then UNION: the later UNION removes all duplicates accumulated so far.
SELECT v FROM a UNION ALL SELECT v FROM a UNION SELECT v FROM b ORDER BY v;
-- UNION then UNION ALL: duplicates added by the last step survive.
SELECT v FROM a UNION SELECT v FROM b UNION ALL SELECT v FROM c ORDER BY v;
-- EXCEPT then EXCEPT.
SELECT v FROM a UNION SELECT v FROM b UNION SELECT v FROM c EXCEPT SELECT v FROM a EXCEPT SELECT v FROM b ORDER BY v;
-- INTERSECT chains.
SELECT v FROM a INTERSECT SELECT v FROM b INTERSECT SELECT v FROM c;
SELECT v FROM a UNION SELECT v FROM b INTERSECT SELECT v FROM c EXCEPT SELECT 4;
-- Long chains of constants.
SELECT 1 UNION SELECT 2 UNION SELECT 3 EXCEPT SELECT 2 UNION ALL SELECT 2 UNION ALL SELECT 2 ORDER BY 1;
SELECT count(*) FROM (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION SELECT 3);
-- Grouping via derived tables changes the order of evaluation.
SELECT v FROM a UNION SELECT * FROM (SELECT v FROM b EXCEPT SELECT v FROM c) ORDER BY v;
SELECT v FROM a EXCEPT SELECT * FROM (SELECT v FROM c UNION SELECT v FROM b) ORDER BY v;
-- Column count must match across the whole chain.
SELECT v FROM a UNION SELECT v FROM b UNION SELECT v, v FROM c;
