-- LIMIT and OFFSET on a compound apply to the whole combined, sorted result.
CREATE TABLE a(v INTEGER);
CREATE TABLE b(v INTEGER);
INSERT INTO a VALUES (5), (1), (9), (3);
INSERT INTO b VALUES (2), (9), (7), (1);

SELECT v FROM a UNION SELECT v FROM b ORDER BY v LIMIT 3;
SELECT v FROM a UNION SELECT v FROM b ORDER BY v LIMIT 3 OFFSET 2;
SELECT v FROM a UNION SELECT v FROM b ORDER BY v DESC LIMIT 2;
SELECT v FROM a UNION ALL SELECT v FROM b ORDER BY v LIMIT 4;
SELECT v FROM a UNION ALL SELECT v FROM b ORDER BY v LIMIT 2, 3;
SELECT v FROM a INTERSECT SELECT v FROM b ORDER BY v LIMIT 1;
SELECT v FROM a EXCEPT SELECT v FROM b ORDER BY v DESC LIMIT 1 OFFSET 1;
-- LIMIT beyond the result, LIMIT 0, negative LIMIT.
SELECT v FROM a UNION SELECT v FROM b ORDER BY v LIMIT 100;
SELECT v FROM a UNION SELECT v FROM b ORDER BY v LIMIT 0;
SELECT count(*) FROM (SELECT v FROM a UNION ALL SELECT v FROM b ORDER BY v LIMIT -1);
-- OFFSET past the end.
SELECT v FROM a UNION SELECT v FROM b ORDER BY v LIMIT 5 OFFSET 50;
-- LIMIT with an expression.
SELECT v FROM a UNION SELECT v FROM b ORDER BY v LIMIT 1 + 1;
SELECT v FROM a UNION SELECT v FROM b ORDER BY v LIMIT (SELECT count(*) FROM a) OFFSET 1;
-- A compound with LIMIT used as a subquery.
SELECT sum(v) FROM (SELECT v FROM a UNION SELECT v FROM b ORDER BY v DESC LIMIT 3);
SELECT (SELECT v FROM a UNION SELECT v FROM b ORDER BY v DESC LIMIT 1 OFFSET 1);
-- Error: LIMIT on a SELECT that is not the last one.
SELECT v FROM a LIMIT 1 UNION SELECT v FROM b;
